services:
    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -   version: '2006-03-01'
                region: '%env(AWS_S3_REGION)%'
                credentials:
                    key: '%env(AWS_S3_KEY)%'
                    secret: '%env(AWS_S3_SECRET)%'

oneup_flysystem:
    adapters:
        app.flysystem_adapter.covers:
            awss3v3:
                client: app.s3_client
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: '%env(AWS_S3_PREFIX)%/covers'
                options:
                    ACL: 'public-read'
        app.flysystem_adapter.attachments:
            awss3v3:
                client: app.s3_client
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: '%env(AWS_S3_PREFIX)%/attachments'
                options:
                    ACL: 'public-read'
                    ContentDisposition: 'attachment'
        app.flysystem_adapter.pictures:
            awss3v3:
                client: app.s3_client
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: '%env(AWS_S3_PREFIX)%/pictures'
                options:
                    ACL: 'public-read'
    filesystems:
        app.filesystem.covers:
            adapter: app.flysystem_adapter.covers
            mount:   app.filesystem.covers
        app.filesystem.attachments:
            adapter: app.flysystem_adapter.attachments
            mount:   app.filesystem.attachments
        app.filesystem.pictures:
            adapter: app.flysystem_adapter.pictures
            mount:   app.filesystem.pictures
