version: '3'

services:
    app:
        build:
            context: ./php-fpm
            args:
                - timezone=${TZ}
        volumes:
            - ../:/srv:rw,cached
            - ../var/log:/srv/var/log:cached
            - ../public/bundles:/srv/public/bundles
            - ../public/assets:/srv/public/assets
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}

    nginx:
        build:
            context: ./nginx
            args:
                - nginx_host=${NGINX_HOST}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        volumes:
            - ../public:/srv/public:ro
            - ./nginx/default.template:/etc/nginx/conf.d/default.template
            - ./logs/nginx:/var/log/nginx
        env_file:
            - .env
        command: /bin/bash -c "envsubst '$$NGINX_HOST'
            < /etc/nginx/conf.d/default.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"

    postgres:
        build:
            context: ./database
            dockerfile: Dockerfile.postgresql
        volumes:
            - ./.data/postgresql:/var/lib/postgresql/data:rw
        env_file:
            - .env
        ports:
            - "5432:5432"
