App\Entity\Attachment:
    attributes:
        id:
            groups: ['lesson_details', 'attachments_list']
        name:
            groups: ['lesson_details', 'attachments_list']
        fileName:
            groups: ['lesson_details', 'attachments_list']
        mimeType:
            groups: ['lesson_details', 'attachments_list']
